### ISSUE TITLE
timestamp with DDATA message

### ISSUE THREAD

**Issue by BasSwildens** [thomassorensen2650/node-red-contrib-mqtt-sparkplug-plus#1]
Hi Thomas,

Really nice job on this Sparkplug node with node-red! Maybe it would be possible to edit the example message with this structure to add a timestamp to the individual metric.

```
{
    "metrics": [
        {
            "timestamp": 1630575884246,
            "name": "groep1/snelheid",
            "value": 11
        },
        {
            "timestamp": 1630575884256,
            "name": "groep1/positie",
            "value": 12
        }
    ]
}
```

**Comment by thomassorensen2650** [comment]
Hi

Thank you for the kind words.

Good point, I'll update the documentation with information about all the optional parameters. I can also see that I need to do some epoch time conversion when timestamp are provided in a Date Object format - I'll include that in the next release. 

I have already made a bunch of other small fixes, and there are still a few more things I want to fix before I release a new version, but hopefully I'll have time doing the weekend.

Thanks for the feedback!

**Comment by thomassorensen2650** [comment]
If you still need support for custom timestamp on message level, then let me know. I'll close this ticket for now.
