### ISSUE TITLE
Primary SCADA buffering

### ISSUE THREAD

**Issue by kumaravel2312** [thomassorensen2650/node-red-contrib-mqtt-sparkplug-plus#2]
Hi, on the instructions for the mqtt-sparkplug-broker, it says 

"Enable Store Forward
This will enable store forward if the Primary SCADA is offline

Destination
This is the name of the Primary SCADA. If store forward is enabled and the STATE/[PRIMARY SCADA NAME] is OFFLINE, then data will be buffered until connection is reestablished."

I have setup the context but what does it mean by Primary SCADA? If I input a value (name) in the destination, the mqtt-sparkplug-device node never connects to my mqtt server and says destination offline.

Could you please point me in the right direction?

![image](https://user-images.githubusercontent.com/86070742/149545579-46fd6579-3d5d-461f-a2ac-5c02e0d229dd.png)

![image](https://user-images.githubusercontent.com/86070742/149545816-ed41947e-51b5-41c6-8d3a-391bc76767e1.png)

**Comment by thomassorensen2650** [comment]
You can find the Sparkplug specification here: [Sparkplug B](https://www.eclipse.org/tahu/spec/Sparkplug%20Topic%20Namespace%20and%20State%20ManagementV2.2-with%20appendix%20B%20format%20-%20Eclipse.pdf)

You need a complient Sparkplug B destination that sets a STATE/[WHATEVER NAME YOU DEFINE] to ONLINE before it will send data (this is all part of the Sparkplug specification) . If you don't have a destination system that supports that (e.g. Ignition, OSISoft PI or another system that supports this functionally) then you can't buffer this way, and you should keep that open unchecked.
