### ISSUE TITLE
Does this node support "Shared Subscriptions" with hivemq?

### ISSUE THREAD

**Issue by avgas3** [thomassorensen2650/node-red-contrib-mqtt-sparkplug-plus#20]
If I set up an MQTT In node with the topic "$share/myshare/spBv1.0/+/DBIRTH/+/+", I get messages for each publish.

If i do the same with the Sparkplug In node, I do not. 

Is this intended? Can this be changed? I would love to be able to leverage multiple node red instances to load balance.

**Comment by thomassorensen2650** [comment]
When you use the MQTT In node, do you select MQTT5 Protocol for the broker connection?
