### ISSUE TITLE
My Device = Ќ���0  testing/test1 P  testing/test2 P

### ISSUE THREAD

**Issue by alexanderberthel** [thomassorensen2650/node-red-contrib-mqtt-sparkplug-plus#21]
Hi,

when using the "mqtt sparkplug device" node with the Simple Device example I get the above Message in the MQTT Explorer. 
What am I doing wrong? 
NR V 3.0.2
node-red-contrib-mqtt-sparkplug-plus V 1.4.0

all running in an Ubuntu 22 VM

Many Thanks

**Comment by thomassorensen2650** [comment]
Sparkplug messages are send as a binary payload.

**Comment by alexanderberthel** [comment]
Hello,
Thank you very much for the quick reply. I am quite new to Node Red. 
What is necessary to transfer the messages in a format so that it is readable for people in the MQTT Explorer. Can I set this in the MQTT Explorer or do I have to send the data differently?  I can also ask someone I know. What are the keywords I have to ask to find a solution to my problem?
Thanks a lot!

**Comment by BasSwildens** [comment]
Try to find a MQTT client with buildin sparkplug decoding. I use [MQTT.fx](https://softblade.de/en/mqtt-fx/)

![Capture](https://user-images.githubusercontent.com/38854481/229538532-37e13828-d524-4194-b6f5-99e505ecf9c6.JPG)

**Comment by alexanderberthel** [comment]
that works. many thanks.
