### ISSUE TITLE
Date as a String

### ISSUE THREAD

**Issue by jfaigan** [thomassorensen2650/node-red-contrib-mqtt-sparkplug-plus#28]
Hello,

I am trying to pass a date value as a String.  The metric is configured thusly:
![image](https://github.com/thomassorensen2650/node-red-contrib-mqtt-sparkplug-plus/assets/14929031/6864dfe4-d453-471c-ad98-496ce00eab7e)

I am receiving the following error:
![image](https://github.com/thomassorensen2650/node-red-contrib-mqtt-sparkplug-plus/assets/14929031/afdbbc54-5776-437d-8eb8-40a52b08a15d)

I understand that the value is a valid date, however, I want this value to be passed as a string to the downstream device.

This error is generated when using the MQTT Sparkplug Out node for a DCMD.

Is there anything I can do to avoid this?  Is there any escape characters that I can use to force the value through as a string?

Thanks in advance.

**Comment by thomassorensen2650** [comment]
That definitely sounds like a bug. Would it be possible for you to create a small flow that shows the issue and attach to this issue.

**Comment by jfaigan** [comment]
Hi Thomas,

My apologies.  After trying to set up the sample flow I realized that it is just the data presenting itself in the debug as a string when if fact the source data is indeed a date.  I changed my source data to be a string and I am no longer having the issue.

Thank you for reaching out.

This ticket can be closed.

Regards,
Joel
