### ISSUE TITLE
Inconsistent data when using definition only at start

### ISSUE THREAD

**Issue by archerixx** [thomassorensen2650/node-red-contrib-mqtt-sparkplug-plus#32]
Hi,

I implemented solution, where I defined "definition" programmaticaly at first message together with metrics, then just continued using metrics after that. (like it was mentioned in documentation)
It happens that some of data get lost in transition when sending it like that.

I then tried using definition in each message and with it, data was consistend, no transition problems.

Is there any chance to look into this ?

**Comment by thomassorensen2650** [comment]
Hi,

Sorry, need a bit more information. what is the issue you are having.. What is the destination for the data? and what behavior do you see that you don't believe is normal?

**Comment by archerixx** [comment]
Issue was that data on SCADA platform (Ignition) was not showing on every data interval. I figured that it was connection issue.

Strange part was that whenever I sent data with "definition" attached to Sparkplug metadata, it would appear on SCADA. Without it, there would be some gaps between data intervals. (I am sending data every 20 seconds, and sometimes data would refresh only every 40 seconds).
Could be that some parts of metrics got lost in transition and Ignition could not parse things correctly.
