### ISSUE TITLE
Dynamic definition for DataSet

### ISSUE THREAD

**Issue by archerixx** [thomassorensen2650/node-red-contrib-mqtt-sparkplug-plus#42]
Hi,

I tested out new dataType DataSet, but I was not able create it dynamicly through Definition.
Only way to create it was through MQTT sparkplug device node, without having "Send BIRTH" activated.

Are there some restriction about it on how it is created currently or just missed out ?

**Comment by thomassorensen2650** [comment]
Hey, 

Any way you can create a small example flow that shows the problem?

**Comment by thomassorensen2650** [comment]
Ahh wait, I can see the issue. I'll create a quick fix

**Comment by thomassorensen2650** [comment]
It is fixed in 5d4fcd8  will see if I can get a new version out soon

**Comment by thomassorensen2650** [comment]
Fixed in V2.0.2
