### ISSUE TITLE
Support for Uint Data Types

### ISSUE THREAD

**Issue by 314PITester** [thomassorensen2650/node-red-contrib-mqtt-sparkplug-plus#53]
The Node works really well, so I wanted to say thank you for that, but the SparkPlug B protocol supports Uint Data Types.  Any chance you guys could build in support for these?  It would be greatly appreciated.

Thanks,

**Comment by 314PITester** [comment]
Awesome.  Than you.  I had sent you a message then noticed I could just open a request here so if you see that message over on Node-Red forums you can ignore it.  

When do you think you'll have another release?  Just curious on a few things I'm working on and trying to get a plan around my deployment.

**Comment by thomassorensen2650** [comment]
This has been added in V2.1.1.

**Comment by 314PITester** [comment]
This is no longer failing when sending Uint data types.  Thank you for updating this so quickly.
