### ISSUE TITLE
NodeJS version compatibility

### ISSUE THREAD

**Issue by archerixx** [thomassorensen2650/node-red-contrib-mqtt-sparkplug-plus#62]
Hi,

Is it possible to make version of this module that is compatible with NodeJS version v12.22.12 (which is hard stuck on our Siemens PLC), either making version of this module here or me making some Fork out of it ?

Thanks

**Comment by thomassorensen2650** [comment]
Did you already look into what (if any) dependencies needs to be downgraded in package.json?

**Comment by archerixx** [comment]
Sorry for late response. These are packages that are unsupported for NodeJS v12.22.12:

package: 'https-proxy-agent@7.0.4',
package: 'mocha@10.4.0',
package: 'node-red-node-test-helper@0.3.4',
package: 'agent-base@7.1.1',
package: 'supertest@7.0.0',
package: 'superagent@9.0.2'

I used packages from version 1.4.1 and built your 2.1.7 release version. Seems that all fine with node-red and package, but I will test throughout week and let you know.

**Comment by archerixx** [comment]
Lib is working fine with previously mentioned packages.
