### ISSUE TITLE
sparkplug node error

### ISSUE THREAD

**Issue by dongzi114** [thomassorensen2650/node-red-contrib-mqtt-sparkplug-plus#73]
I always get errors when using related functions. The error message is as follows. May I ask which aspect of the problem it may be?

node:Sparkplug Nodemsg : string[70]
"Unable to encode DBIRTH message.the error isError: interior hyphen"

**Comment by thomassorensen2650** [comment]
Hmm interesting. Do you have an example flow?

My initial thought is that it's trying to encode a datetime string as DateTime, but it requires some more investigation.
