### ISSUE TITLE
Dynamic metric definitions - can msg.definition be an array ? 

### ISSUE THREAD

**Issue by industrialinternet** [thomassorensen2650/node-red-contrib-mqtt-sparkplug-plus#74]
Thomas thanks for your continued good work on Sparkplug-plus.
For my use case I have 100s of metrics each with at least two properties or more these are stored as JSON
So the question for me is, can msg.definition be an array as in the below?
Or does each metric need to be sent separately when using Dynamic metric definitions?

Thanks

```
msg ={
  "definition" : [
    {
      "outdoor_pallet_area_1/externalTemperature": {
        "dataType": "Float",
        "properties": {
          "engUnits": {
            "type": "String",
            "value": "C"
          },
          "devEUI": {
            "type": "String",
            "value": "A81758FFFE0375FF"
          }
        }
      }
    },
    {
      "outdoor_pallet_area_1/humidity": {
        "dataType": "UInt16",
        "properties": {
          "engUnits": {
            "type": "String",
            "value": "%RH"
          },
          "devEUI": {
            "type": "String",
            "value": "A81758FFFE0375FF"
          }
        }
      }
    }
  ]
}
```

**Comment by thomassorensen2650** [comment]
Im not sure that I understand the issue. Definition is an object that can have multiple attributes.   Why do you want it to be an array? 

```
msg = {
    "definition": {
        "outdoor_pallet_area_1/externalTemperature": {
            "dataType": "Int32",
            "properties": {
                "engUnits": {
                    "type": "String",
                    "value": "inHg"
                }
            }
            },
            "outdoor_pallet_area_1/humidity": {
                "dataType": "UInt16",
                "properties": {
                    "engUnits": {
                        "type": "String",
                        "value": "%RH"
                    }
                }
            }
    }
}
```

**Comment by industrialinternet** [comment]
Hi it would just make my processing a little easier but no worries.
BTW have you tested with Ignition SCADA? 
I looked at sparkplug validation tool that looks a little too much so I'm going to use Ignition.
Again thanks for your work on this node much apricated.

**Comment by thomassorensen2650** [comment]
If you ever get that Sparkplug validation tool to work let me know, that would be super interesting.. Yes, multiple people use the nodes with Ignition.

I will close this issue, as I dont see any action.

**Comment by industrialinternet** [comment]
Thanks.
