### ISSUE TITLE
Is it possible to leave device_id empty?

### ISSUE THREAD

**Issue by FluidUnion** [thomassorensen2650/node-red-contrib-mqtt-sparkplug-plus#84]
Sorry if this is the wrong place to ask, couldn't find a forum or something like it.

I would like to use the "mqtt sparkplug device" node without it automatically making a device id. I don't know how to do this in node-red or if it is even possible if you use the "mqtt sparkplug device" node.

**Comment by thomassorensen2650** [comment]
No unfortunately that's not possible currently. It's something that has been discussed, and that might be added in the future, but is has not been implemented yet.

**Comment by FluidUnion** [comment]
ok, thank you very much for your clarification
